//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlog
    {
        public string Title { get; set; }
        public string Tags { get; set; }
        public string PostedBy { get; set; }
        public string Date { get; set; }
        public string Content { get; set; }
        public string Summary { get; set; }
        public int PostID { get; set; }
    }
}
